[tool.poetry]
name = "Sample API"
version = "0.1"
description = ""
authors = ["Inigo Allende"]

[tool.poetry.dependencies]
python = "^3.8.10"
flask = "^2.0.1"
gunicorn = "^20.1.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
